/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WalletRouteImport } from './routes/wallet'
import { Route as TournamentsRouteImport } from './routes/tournaments'
import { Route as StatsRouteImport } from './routes/stats'
import { Route as RecentRouteImport } from './routes/recent'
import { Route as PromotionsRouteImport } from './routes/promotions'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as FavoritesRouteImport } from './routes/favorites'
import { Route as FairnessRouteImport } from './routes/fairness'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CasinoIndexRouteImport } from './routes/casino.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as GamesLiveRouteImport } from './routes/games.live'
import { Route as GamesCrashRouteImport } from './routes/games.crash'
import { Route as CasinoCategoryRouteImport } from './routes/casino.$category'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminTransactionsRouteImport } from './routes/admin.transactions'
import { Route as AdminDepositsRouteImport } from './routes/admin.deposits'
import { Route as GamesLiveIndexRouteImport } from './routes/games.live.index'
import { Route as GamesLiveSlugRouteImport } from './routes/games.live.$slug'

const WalletRoute = WalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => rootRouteImport,
} as any)
const TournamentsRoute = TournamentsRouteImport.update({
  id: '/tournaments',
  path: '/tournaments',
  getParentRoute: () => rootRouteImport,
} as any)
const StatsRoute = StatsRouteImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => rootRouteImport,
} as any)
const RecentRoute = RecentRouteImport.update({
  id: '/recent',
  path: '/recent',
  getParentRoute: () => rootRouteImport,
} as any)
const PromotionsRoute = PromotionsRouteImport.update({
  id: '/promotions',
  path: '/promotions',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const FavoritesRoute = FavoritesRouteImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => rootRouteImport,
} as any)
const FairnessRoute = FairnessRouteImport.update({
  id: '/fairness',
  path: '/fairness',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CasinoIndexRoute = CasinoIndexRouteImport.update({
  id: '/casino/',
  path: '/casino/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const GamesLiveRoute = GamesLiveRouteImport.update({
  id: '/games/live',
  path: '/games/live',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesCrashRoute = GamesCrashRouteImport.update({
  id: '/games/crash',
  path: '/games/crash',
  getParentRoute: () => rootRouteImport,
} as any)
const CasinoCategoryRoute = CasinoCategoryRouteImport.update({
  id: '/casino/$category',
  path: '/casino/$category',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTransactionsRoute = AdminTransactionsRouteImport.update({
  id: '/transactions',
  path: '/transactions',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDepositsRoute = AdminDepositsRouteImport.update({
  id: '/deposits',
  path: '/deposits',
  getParentRoute: () => AdminRoute,
} as any)
const GamesLiveIndexRoute = GamesLiveIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => GamesLiveRoute,
} as any)
const GamesLiveSlugRoute = GamesLiveSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => GamesLiveRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/fairness': typeof FairnessRoute
  '/favorites': typeof FavoritesRoute
  '/profile': typeof ProfileRoute
  '/promotions': typeof PromotionsRoute
  '/recent': typeof RecentRoute
  '/stats': typeof StatsRoute
  '/tournaments': typeof TournamentsRoute
  '/wallet': typeof WalletRoute
  '/admin/deposits': typeof AdminDepositsRoute
  '/admin/transactions': typeof AdminTransactionsRoute
  '/admin/users': typeof AdminUsersRoute
  '/casino/$category': typeof CasinoCategoryRoute
  '/games/crash': typeof GamesCrashRoute
  '/games/live': typeof GamesLiveRouteWithChildren
  '/admin/': typeof AdminIndexRoute
  '/casino/': typeof CasinoIndexRoute
  '/games/live/$slug': typeof GamesLiveSlugRoute
  '/games/live/': typeof GamesLiveIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/fairness': typeof FairnessRoute
  '/favorites': typeof FavoritesRoute
  '/profile': typeof ProfileRoute
  '/promotions': typeof PromotionsRoute
  '/recent': typeof RecentRoute
  '/stats': typeof StatsRoute
  '/tournaments': typeof TournamentsRoute
  '/wallet': typeof WalletRoute
  '/admin/deposits': typeof AdminDepositsRoute
  '/admin/transactions': typeof AdminTransactionsRoute
  '/admin/users': typeof AdminUsersRoute
  '/casino/$category': typeof CasinoCategoryRoute
  '/games/crash': typeof GamesCrashRoute
  '/admin': typeof AdminIndexRoute
  '/casino': typeof CasinoIndexRoute
  '/games/live/$slug': typeof GamesLiveSlugRoute
  '/games/live': typeof GamesLiveIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/fairness': typeof FairnessRoute
  '/favorites': typeof FavoritesRoute
  '/profile': typeof ProfileRoute
  '/promotions': typeof PromotionsRoute
  '/recent': typeof RecentRoute
  '/stats': typeof StatsRoute
  '/tournaments': typeof TournamentsRoute
  '/wallet': typeof WalletRoute
  '/admin/deposits': typeof AdminDepositsRoute
  '/admin/transactions': typeof AdminTransactionsRoute
  '/admin/users': typeof AdminUsersRoute
  '/casino/$category': typeof CasinoCategoryRoute
  '/games/crash': typeof GamesCrashRoute
  '/games/live': typeof GamesLiveRouteWithChildren
  '/admin/': typeof AdminIndexRoute
  '/casino/': typeof CasinoIndexRoute
  '/games/live/$slug': typeof GamesLiveSlugRoute
  '/games/live/': typeof GamesLiveIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/fairness'
    | '/favorites'
    | '/profile'
    | '/promotions'
    | '/recent'
    | '/stats'
    | '/tournaments'
    | '/wallet'
    | '/admin/deposits'
    | '/admin/transactions'
    | '/admin/users'
    | '/casino/$category'
    | '/games/crash'
    | '/games/live'
    | '/admin/'
    | '/casino/'
    | '/games/live/$slug'
    | '/games/live/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/fairness'
    | '/favorites'
    | '/profile'
    | '/promotions'
    | '/recent'
    | '/stats'
    | '/tournaments'
    | '/wallet'
    | '/admin/deposits'
    | '/admin/transactions'
    | '/admin/users'
    | '/casino/$category'
    | '/games/crash'
    | '/admin'
    | '/casino'
    | '/games/live/$slug'
    | '/games/live'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/fairness'
    | '/favorites'
    | '/profile'
    | '/promotions'
    | '/recent'
    | '/stats'
    | '/tournaments'
    | '/wallet'
    | '/admin/deposits'
    | '/admin/transactions'
    | '/admin/users'
    | '/casino/$category'
    | '/games/crash'
    | '/games/live'
    | '/admin/'
    | '/casino/'
    | '/games/live/$slug'
    | '/games/live/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AuthRoute: typeof AuthRoute
  FairnessRoute: typeof FairnessRoute
  FavoritesRoute: typeof FavoritesRoute
  ProfileRoute: typeof ProfileRoute
  PromotionsRoute: typeof PromotionsRoute
  RecentRoute: typeof RecentRoute
  StatsRoute: typeof StatsRoute
  TournamentsRoute: typeof TournamentsRoute
  WalletRoute: typeof WalletRoute
  CasinoCategoryRoute: typeof CasinoCategoryRoute
  GamesCrashRoute: typeof GamesCrashRoute
  GamesLiveRoute: typeof GamesLiveRouteWithChildren
  CasinoIndexRoute: typeof CasinoIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wallet': {
      id: '/wallet'
      path: '/wallet'
      fullPath: '/wallet'
      preLoaderRoute: typeof WalletRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tournaments': {
      id: '/tournaments'
      path: '/tournaments'
      fullPath: '/tournaments'
      preLoaderRoute: typeof TournamentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stats': {
      id: '/stats'
      path: '/stats'
      fullPath: '/stats'
      preLoaderRoute: typeof StatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recent': {
      id: '/recent'
      path: '/recent'
      fullPath: '/recent'
      preLoaderRoute: typeof RecentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/promotions': {
      id: '/promotions'
      path: '/promotions'
      fullPath: '/promotions'
      preLoaderRoute: typeof PromotionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favorites': {
      id: '/favorites'
      path: '/favorites'
      fullPath: '/favorites'
      preLoaderRoute: typeof FavoritesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fairness': {
      id: '/fairness'
      path: '/fairness'
      fullPath: '/fairness'
      preLoaderRoute: typeof FairnessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/casino/': {
      id: '/casino/'
      path: '/casino'
      fullPath: '/casino/'
      preLoaderRoute: typeof CasinoIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/games/live': {
      id: '/games/live'
      path: '/games/live'
      fullPath: '/games/live'
      preLoaderRoute: typeof GamesLiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games/crash': {
      id: '/games/crash'
      path: '/games/crash'
      fullPath: '/games/crash'
      preLoaderRoute: typeof GamesCrashRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/casino/$category': {
      id: '/casino/$category'
      path: '/casino/$category'
      fullPath: '/casino/$category'
      preLoaderRoute: typeof CasinoCategoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/transactions': {
      id: '/admin/transactions'
      path: '/transactions'
      fullPath: '/admin/transactions'
      preLoaderRoute: typeof AdminTransactionsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/deposits': {
      id: '/admin/deposits'
      path: '/deposits'
      fullPath: '/admin/deposits'
      preLoaderRoute: typeof AdminDepositsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/games/live/': {
      id: '/games/live/'
      path: '/'
      fullPath: '/games/live/'
      preLoaderRoute: typeof GamesLiveIndexRouteImport
      parentRoute: typeof GamesLiveRoute
    }
    '/games/live/$slug': {
      id: '/games/live/$slug'
      path: '/$slug'
      fullPath: '/games/live/$slug'
      preLoaderRoute: typeof GamesLiveSlugRouteImport
      parentRoute: typeof GamesLiveRoute
    }
  }
}

interface AdminRouteChildren {
  AdminDepositsRoute: typeof AdminDepositsRoute
  AdminTransactionsRoute: typeof AdminTransactionsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminDepositsRoute: AdminDepositsRoute,
  AdminTransactionsRoute: AdminTransactionsRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface GamesLiveRouteChildren {
  GamesLiveSlugRoute: typeof GamesLiveSlugRoute
  GamesLiveIndexRoute: typeof GamesLiveIndexRoute
}

const GamesLiveRouteChildren: GamesLiveRouteChildren = {
  GamesLiveSlugRoute: GamesLiveSlugRoute,
  GamesLiveIndexRoute: GamesLiveIndexRoute,
}

const GamesLiveRouteWithChildren = GamesLiveRoute._addFileChildren(
  GamesLiveRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AuthRoute: AuthRoute,
  FairnessRoute: FairnessRoute,
  FavoritesRoute: FavoritesRoute,
  ProfileRoute: ProfileRoute,
  PromotionsRoute: PromotionsRoute,
  RecentRoute: RecentRoute,
  StatsRoute: StatsRoute,
  TournamentsRoute: TournamentsRoute,
  WalletRoute: WalletRoute,
  CasinoCategoryRoute: CasinoCategoryRoute,
  GamesCrashRoute: GamesCrashRoute,
  GamesLiveRoute: GamesLiveRouteWithChildren,
  CasinoIndexRoute: CasinoIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
